### ISSUE TITLE
can this xblock-poll run in xblock-sdk environment？

### ISSUE THREAD

**Issue by yinhuanyi** [open-craft/xblock-poll#76]
can this xblock-poll run in xblock-sdk environment？I try to run integrate this in xblock-sdk，but does not success

**Comment by kaizoku** [comment]
Hi @yinhuanyi, yes, this will run in the `xblock-sdk`.
What is the error you're seeing when you install `xblock-poll` into `xblock-sdk`?

I got `xblock-poll` setup in the `xblock-sdk` with the xblock-sdk with the [sdk install setup](https://github.com/edx/xblock-sdk/#installation), and then installing xblock-poll's requirements, followed by xblock-poll itself:

```sh
virtualenv .venv
source .venv/bin/activate
cd xblock-sdk
make install
cd ../xblock-poll
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -e .
```

There were some python requirements missing until I explicitly installed `xblock-poll`'s requirements files as well. Is this the cause of the issue you're seeing?

**Comment by yinhuanyi** [comment]
ok , Thank you

**Comment by yinhuanyi** [comment]
and another question: How can I integrate MIT Scratch into xblock based on xblock-poll? Can we do this

**Comment by xitij2000** [comment]
@yinhuanyi How would you want them to be integrated? I do not think this is possible out of the box, but it is certainly something that can be developed, and contributed to this repo.
