### ISSUE TITLE
Publish this package to PyPI

### ISSUE THREAD

**Issue by aht007** [open-craft/xblock-poll#98]
## Background

This package is currently installed into edx-platform [directly from GitHub](github.com/openedx/edx-platform/tree/master/requirements/edx/github.in). This is non-ideal because:
* GitHub-hosted requirements take significantly longer (> 4x) to install than PyPI-hosted requirements
* GitHub-hosted requirement pins cannot be upgraded using edX's standard `make upgrade` workflow.

## Request

* Audit this package's `setup.py` to make sure it looks right before publishing. You can test it out by:
  * creating a virtual environment
  * installing package requirements 
  * running `python setup.py sdist bdist_wheel`
  * checking the contents of the generated `dist/` folder. The folder should contain a .tar.gz that can be unpacked, yielding the contents of what would be pushed to PyPI. The unpacked .tar.gz should include all Python source files (other than test files) as well as a LICENSE and any assets/resources needed for the block to work.
* Publish this package to PyPI whenever a release happens.
* Trigger a release to publish this package to PyPI

**Comment by pkulkark** [comment]
Thanks @aht007. We'll create a task on our end to look into this and update here.

**Comment by kdmccormick** [comment]
Hey @pkulkark , do you think you will be able to finish this soon?

**Comment by pkulkark** [comment]
@kdmccormick Sorry for the delay. This is nearly ready but we're trying to tie up a few loose ends. I'll post here once it's ready.

**Comment by kdmccormick** [comment]
All good, thanks!

**Comment by pkulkark** [comment]
@kdmccormick This is done. We've added the required workflow to publish to pypi whenever a release happens, and triggered it.
